method: "comm"
gex_encoder: "S"
img_encoder: "S"
projection_dim: 256
embed_dim: 256  # Common embedding dimension for fusion
n_heads: 8      # Number of attention heads
n_layers: 1     # Number of transformer layers
fusion: "x-attn" # Fusion strategy (concat or x-attn)
pool: "mean"     # Pooling strategy (cls or mean)
img_embed_dim: 1536
gex_embed_dim: 512
temperature: 0.07
checkpoint_split: "preL"

