# Nicheformer model configuration for 1K donors
model_name: nicheformer
dim_model: 96
nheads: 8
dim_feedforward: 384
nlayers: 2
dropout: 0.0
subset: "nf_1000donors"

# Additional nicheformer parameters
batch_first: true
masking_p: 0.15
n_tokens: 20340
context_length: 1500
warmup: 2000
autoregressive: false
pool: null
supervised_task: false
learnable_pe: true
specie: false
assay: false
modality: false
contrastive: false
