method: "simsiam"
img_embed_dim: 1536
gex_embed_dim: 512
projection_dim: 256
hidden_dims: [512, 512]
dropout: 0.1
use_batchnorm: true
projection_hidden_dim: 512
pred_dim: 128
checkpoint_path: "simsiam/best_simsiam_lr1e-05_wd1e-05-epoch=91-val_loss=-0.9718.ckpt"