method: "vicreg"
gex_encoder: "S"
img_encoder: "S"
projection_dim: 256  # Match the checkpoint dimensions
sim_coeff: 25.0
std_coeff: 25.0
cov_coeff: 1.0 
img_embed_dim: 1536
gex_embed_dim: 512
checkpoint_split: "preL"
